### ISSUE TITLE
a error when use pretraining

### ISSUE THREAD

**Issue by JingsenZhang** [ustcljb/ncf_pytorch#1]
hi，
when i use NeuMF model with pretraining, a error arises like this:

AttributeError: Can't get attribute 'GMF' on <module 'main' from 'NeuMF.py'>
![image](https://user-images.githubusercontent.com/36886184/90467582-1c2f2200-e147-11ea-9a85-43ddc9c36549.png)

in code:
![image](https://user-images.githubusercontent.com/36886184/90467604-294c1100-e147-11ea-81f9-a374c57b500d.png)
do you know how to solve it? thank you very much!

**Comment by ustcljb** [comment]
Could you provide more information? Like what device are you using, CPU or GPU? It might have something to do with the model saving and loading process.

**Comment by ustcljb** [comment]
Now it should be OK. Could you rerun the GMF.py and MLP.py scripts again and then the NeuMF model with pretrained? I modified the model saving and loading process. Please refer https://pytorch.org/tutorials/beginner/saving_loading_models.html for more details.

**Comment by JingsenZhang** [comment]
i have run the code on both CPU and GPU, but the error still occurs.

i so think it is relevant to the process of saving and loading, and i will continue to study it .

thank you !

**Comment by ustcljb** [comment]
You are welcome! I changed the model saving and loading by using state_dict and ran it in couple of devices. It should work fine now.

**Comment by JingsenZhang** [comment]
yeah!
it's ok!
thank you!

**Comment by JingsenZhang** [comment]
Hello!
I have an interesting discovery that the NeuMF with pretraining doesn't perform as well as the non-pretraining version. 
it's strange.
(the first image is pretraining version, the second is no-pretraining)
![image](https://user-images.githubusercontent.com/36886184/90701428-f9be1580-e2ba-11ea-8096-fcdf86fdc84d.png)
![image](https://user-images.githubusercontent.com/36886184/90701484-207c4c00-e2bb-11ea-914b-eeaa7dca8007.png)
